services:
  - type: web
    name: quiz-website
    runtime: node
    plan: free
    buildCommand: npm install && cd frontend && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
